### ISSUE TITLE
Late Assignments do not show

### ISSUE THREAD

**Issue by sapblatt11** [HyDevelop/VeracrossAnalyzer.Client#3]
Assignments that are marked as late do not show up in Veracross analyzer. 

If I understood the code I would try to fix it.
![56CABB08-6329-45E8-BA57-33172D095E16](https://user-images.githubusercontent.com/15711797/72911596-572fbb00-3d08-11ea-87ed-8727120a1a26.png)
![46F137EE-FB1C-4305-9E09-90FD55E2DB95](https://user-images.githubusercontent.com/15711797/72911599-57c85180-3d08-11ea-91b1-3961272ff627.png)

**Comment by hykilpikonna** [comment]
This is because there is no specific code to detect whether or not an assignment is late yet.
I'll try adding it when I have time (probably this weekend).

If you want to look at the source code of assignment entries, they are in `/src/pages/overall/overall-course/assignment-entry/`. I'm pretty sure that the `Assignment` class has to be modified as well since I didn't include unused data variables for memory optimization.

Also, can you inspect the assignments page and post the JSON of the late assignment? Since I don't have any late assignments, and there is no API documentation for Veracross, so IDK where "late" is defined in the JSON.

It should look something like this:
![image](https://user-images.githubusercontent.com/22280294/72932332-90c6ed00-3d2d-11ea-915c-e69f257832df.png)

Thanks.

**Comment by sapblatt11** [comment]
Ok, I did some looking around. When an assignment is late 2 things change in the assignment json.

Regular assignment:
`"completion_status_id": 3,
 "completion_status": "Complete",`

Late Assignment:
`"completion_status_id": 7,
 "completion_status": "Late",`

So the completion status changes to 7 and the status becomes "Late".
Here is the full assignment json in case I missed something. 
https://gist.github.com/sapblatt11/5fdc35269c67c1deae371185055c48bc

**Comment by hykilpikonna** [comment]
Fixed
